language: java
sudo: false
os:
  - linux
jdk:
  - oraclejdk8
install:
  #Test to see if builds
  - export CLASSPATH="$CLASSPATH:jars/antlr-4.5.3-complete.jar"
  - java org.antlr.v4.Tool src/com/juliar/parser/juliar.g4 -o . -no-listener -package com.juliar.parser -visitor
  #Test to see if JuliarCompilerTest compiles
  - java src/com/juliar/test/JuliarCompilerTest.java -o .
  #Test to see if JuliarCompilerTest passes
  - java JuliarCompilerTest.class
