language: java
sudo: true
jdk:
  - oraclejdk8

os:
  - linux

before_script:
 - chmod +x BuildEverything.sh


script:
  - ./BuildEverything.sh

notifications:
  slack: juliarlang:z7GTm7XhwjuvwIb9oYKvFdWN