version: 0.0.{build}

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

build_script:
  - BuildEverything.bat

test: off

cache:
  - C:\Users\appveyor\.m2

build:
   verbosity: detailed